--- 
title: "Compiled Lectures for Regression Modelling"
author: "compiled by Jonathan Godfrey"
date: "updated on `r format(Sys.Date(), '%d %B %Y')`"
documentclass: book
bibliography: [book.bib,RPackages.bib]
biblio-style: apalike
link-citations: yes
description: "The content used in lecture presentations compiled into one volume"
---

# Preface {-}

These notes were used for lectures for the course 161.251 Regression Modelling taught at Massey University by a host of different staff; the relative constant in recent years is Jonathan Godfrey who is responsible for these notes.


We use R in almost every lecture; you should be able to run the code on your own. You should follow the current Stream instructions to get your own installation of R and RStudio set up for the course. 

The material that follows makes use of `tidyverse` packages. Graphs are made using a mixture of base R graphics and ggplot functions, with the choice being made on the basis of convenience. There is no sense using a lot of effort if the graph is simple and will only be seen by the analyst. More effort is warranted if the graph is likely to be enriched or used for a presentation.

Please ask for help if you don't understand the R code being demonstrated.

```{r getLibraries, include=FALSE}
library(tidyverse, )
library(broom)
library(knitr)
library(rmarkdown)
write_bib(file="RPackages.bib")
```
